project:
  type: website

website:
  title: "Customer Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectanalysis.qmd
        text: Project Analysis - Customer Transaction Data
      - href: assignment1.qmd
        text: Assignment 1
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

