{
  "hash": "3ed250813495e9160cee97132c0c3e6b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Project Analysis - Customer Transaction Data\"\n\nauthor: \"Cheng Chun Chieh\"\n\ndate: \"8 May 2024\"\ndate-modified: \"last-modified\"\n\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n  code-fold: true\n  \neditor: visual\n---\n\n\n# 1. Getting Started\n\nFirst loading the packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(ggstatsplot,plotly, patchwork, hrbrthemes, ggridges, ggrepel, tidyverse, ggpubr, scales, colorspace, ggdist)\n```\n:::\n\n\n## 1.1 Reading the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_csv(\"data/updated_data.csv\")\n```\n:::\n\n\nNot sure why, but there are empty columns being loaded. We will remove that. Additionally, we will expand the columns to include the measure values in separate columns, e.g. Retail Price etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  select(-18:-29)\n\ndf_transformed <- df %>%\n  pivot_wider(names_from = `Measure Names`, values_from = `Measure Values`)\n```\n:::\n\n\nStandardise the typing format under Category Description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_transformed <- df_transformed %>%\n  mutate(`Category Description` = case_when(\n    str_detect(`Category Description`, \"Home collection\") ~ \"Home Collection\",\n    str_detect(`Category Description`, \"SKIN CARE\") ~ \"Skin Care\",\n    str_detect(`Category Description`, \"Skin care\") ~ \"Skin Care\",\n    str_detect(`Category Description`, \"ORAL CARE\") ~ \"Oral Care\",\n    TRUE ~ `Category Description`\n  ))\n```\n:::\n\n\n# 2.1 EDA\n\nLet's do some initial statistic counting first to understand the data.\n\n## 2.1 Number of Rows with Net Price = 0 / Customer who received Samples\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_zeros <- df_transformed %>%   \n  filter(`Net Price (SGD)` == 0)\n```\n:::\n\n\nWe have 40,049 observations with net price = 0. Based on the product description, these looks like sample products that are given with the purchase.\n\nLet's do a count of the number of customers and their IDs who received these samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples_per_customer <- num_zeros %>%   \n  group_by(Customer) %>%   \n  summarise(samples_received = n_distinct(`Order No`))\n```\n:::\n\n\nFrom the data - we have 11,329 unique customers who received these samples.\n\nQuick visualisation on the number of samples per customers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=samples_per_customer,         \n       aes(x = samples_received)) +   \n  geom_bar(bins=1,                   \n           boundary = 100,                  \n           color=\"grey25\",                   \n           fill=\"grey90\") +   \n  theme_minimal() +   \n  xlim(0,5) +   \n  ggtitle(\"Samples Per Customers\")\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nCan see that most of them only received 1 samples.\n\nWe remove these samples from the main dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_filtered <- df_transformed %>%   \n  filter(`Net Price (SGD)` != 0) %>%   \n  filter(`Retail Price (SGD)` != 0)\n\ndf_filtered <- df_filtered %>%   \n  mutate(per_discount = (`Item Discount (SGD)` / `Retail Price (SGD)` * 100)) %>%\n  mutate(per_discount = ifelse(is.infinite(per_discount), NA, per_discount))\n```\n:::\n\n\n## 2.2 Checking Customer Data\n\n### 2.1.1 Number of Customers\n\nFirst, lets see how many unique customers are there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_unique_customers <- df_filtered %>%\n  distinct(Customer, `Customer Gender`, Country) %>%\n  mutate(`Customer Gender` = factor(`Customer Gender`),\n         Country = factor(Country)) \n\nsummary(num_unique_customers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Customer       Customer Gender Country   \n Min.   :1000350   F      :8782    MY: 3618  \n 1st Qu.:2116865   M      :2881    SG:17046  \n Median :3471894   Unknown:9001              \n Mean   :3243219                             \n 3rd Qu.:4291294                             \n Max.   :5230122                             \n```\n\n\n:::\n:::\n\n\nThe data comprise 20664 unique customer ID.\n\nOf which, we have 11,663 customers with gender. From these data, we have **8782 Female Customers** and **2881 Male Customers**.\n\n### 2.1.2 Number of Orders and Number of Products\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the total number of products purchased by each customer\nproducts_per_customer <- df_filtered %>%\n  group_by(Customer) %>%\n  summarise(total_num_products = sum(Qty))\n\nsummary(products_per_customer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Customer       total_num_products\n Min.   :1000350   Min.   :    1.00  \n 1st Qu.:2116865   1st Qu.:    1.00  \n Median :3471894   Median :    2.00  \n Mean   :3243219   Mean   :    9.73  \n 3rd Qu.:4291294   3rd Qu.:    3.00  \n Max.   :5230122   Max.   :84799.00  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate the number of orders made by each customer\norders_per_customer <- df_filtered  %>%\n  group_by(Customer) %>%\n  summarise(Freq = n_distinct(`Order No`),\n            Monetary = sum(`Net Price (SGD)`, na.rm = TRUE))\n\nsummary (orders_per_customer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Customer            Freq            Monetary      \n Min.   :1000350   Min.   :  1.000   Min.   :      1  \n 1st Qu.:2116865   1st Qu.:  1.000   1st Qu.:    158  \n Median :3471894   Median :  1.000   Median :    312  \n Mean   :3243219   Mean   :  1.597   Mean   :   1012  \n 3rd Qu.:4291294   3rd Qu.:  1.000   3rd Qu.:    556  \n Max.   :5230122   Max.   :457.000   Max.   :3599713  \n```\n\n\n:::\n:::\n\n\nFor the study here - I just define Freq as the number of orders within the 2 years period, i.e. even if within the same month or week.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nhead(products_per_customer[order(products_per_customer$total_num_products, decreasing = TRUE), ], 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 2\n   Customer total_num_products\n      <dbl>              <dbl>\n 1  3558061              84799\n 2  4497811              15530\n 3  1117958              10630\n 4  3264222               6452\n 5  1678261               1428\n 6  2062441               1390\n 7  1199830               1108\n 8  1664656                720\n 9  2011870                700\n10  1900810                670\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nhead(orders_per_customer[order(orders_per_customer$Monetary, decreasing = TRUE), ], 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 3\n   Customer  Freq Monetary\n      <dbl> <int>    <dbl>\n 1  3558061    20 3599713.\n 2  1117958   457 2505904.\n 3  4497811    14  875207.\n 4  3264222    21  679898.\n 5  1678261    22  349773.\n 6  1494594    57  260759.\n 7  4498726     9  189137.\n 8  1199830    50  158623.\n 9  2126742    60  114673.\n10  2603534    45  108388.\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\nWe may need to filter out these customers subsequently as they do not represent the average customers - also to find out where are they from.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=orders_per_customer, \n       aes(x = Freq)) +\n  geom_bar(bins=20, \n                 boundary = 100,\n                 color=\"grey25\", \n                 fill=\"grey90\") +\n  theme_minimal() +\n  geom_text(stat='count', aes(label=..count..), vjust=-1, size = 2) +\n  xlim(0,20) +\n  ggtitle(\"Count of Number of Orders\")\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### 2.1.3 Calculating Recency\n\nI calculated recency based on the last day of order and the number of days in between then and 14 May 24.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dates <- df_filtered %>%   \n  mutate(`Document Date` = as.Date(as.character(`Document Date`),format='%d/%m/%Y'))  \n\ndate <- as.Date(\"14/May/2024\", format=\"%d/%b/%Y\")\na <- as.numeric(date)     \n\nrecency_per_customer <- df_dates %>%   \n  group_by(Customer) %>%   \n  summarise(recency = a - as.numeric(max(`Document Date`), format=\"%d/%m/%Y\"))  \nsummary(recency_per_customer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Customer          recency     \n Min.   :1000350   Min.   :135.0  \n 1st Qu.:2116865   1st Qu.:267.0  \n Median :3471894   Median :477.0  \n Mean   :3243219   Mean   :473.2  \n 3rd Qu.:4291294   3rd Qu.:667.0  \n Max.   :5230122   Max.   :864.0  \n```\n\n\n:::\n:::\n\n\n### 2.1.4 Checking the mode of purchase and types of products\n\nFirst, to check the summary of the category description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(as.factor(df_filtered$`Category Description`))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Bath and Body  Beauty Accessories Fashion Accessories           Fragrance \n               7957                 283                 129               33688 \n           Haircare     Home Collection             Make up           Oral Care \n               2670                9131                1419                 252 \n          Skin Care \n              10196 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group by customers and create indicator columns\ndf_indicators <- df_filtered %>%\n  group_by(Customer) %>%\n  reframe(\n    retail = ifelse(\"Retail\" %in% `Sales Channel`, \"Yes\", \"No\"),\n    third_party = ifelse(\"3rd Party Marketplaces\" %in% `Sales Channel`, \"Yes\", \"No\"),\n    corp = ifelse(\"Corp Sales\" %in% `Sales Channel`, \"Yes\", \"No\"),\n    website = ifelse(\"eCommerce Stores\" %in% `Sales Channel`, \"Yes\", \"No\"),\n    fragrance = ifelse(\"Fragrance\" %in% `Category Description`, \"Yes\", \"No\"),\n    skincare = ifelse(\"Skin Care\" %in% `Category Description`, \"Yes\", \"No\"),\n    bathbody = ifelse(\"Bath and Body\" %in% `Category Description`, \"Yes\", \"No\"),\n    home = ifelse(\"Home Collection\" %in% `Category Description`, \"Yes\", \"No\"),\n    haircare = ifelse(\"Haircare\" %in% `Category Description`, \"Yes\", \"No\"),\n    makeup = ifelse(\"Make up\" %in% `Category Description`, \"Yes\", \"No\"),\n    oral = ifelse(\"Oral Care\" %in% `Category Description`, \"Yes\", \"No\"),\n    beauty_acc = ifelse(\"Beauty Accessories\" %in% `Category Description`, \"Yes\", \"No\"),\n    fashion_acc = ifelse(\"Fashion Accessories\" %in% `Category Description`, \"Yes\", \"No\")\n    ) \n```\n:::\n\n\n### 2.1.5 Looking across brands\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(as.factor(df_filtered$`Brand Description`))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           3LAB SKINCARE      Masion de L\\x92asie           ACQUA DI PARMA \n                       3                       78                     5359 \n                 AMOUAGE            ANNICK GOUTAL                    AVEDA \n                    1048                     1064                      949 \n       BJORK AND BERRIES        BKR WATER BOTTLES                BOUCHERON \n                     946                       36                       28 \n                 BVLGARI               BY KILLIAN                 BY TERRY \n                     544                     1727                     1103 \n        BYREDO FRAGRANCE                  CHOPARD       CIRE TRUDON CANDLE \n                    5491                        2                     1020 \n       COMME DES GARCONS                    CREED             D.S. & DURGA \n                      36                     2781                      496 \n                DIPTYQUE                  EVE LOM                 FLORAIKU \n                    7946                      663                       80 \n              FORNASETTI           FREDERIC MALLE              GINORI 1735 \n                       5                     2283                       65 \n                  HERMES                HERMETICA               JACK BLACK \n                     963                       40                      676 \n     JUNGSAEMMOOL BEAUTY                   Kayali                LA BRUKET \n                       5                      301                     1701 \n            LEONOR GREYL                    LOEWE          MAISON CRIVELLI \n                     798                      344                      393 \nMAISON FRANCIS KURKDJIAN            MALIN + GOETZ         MATIERE PREMIERE \n                    7818                     2789                       70 \n                    MEMO            MILLER HARRIS        MONCLER FRAGRANCE \n                     739                       46                      371 \n                 OLAPLEX               OMOROVICZA               PENHALIGON \n                     225                       45                     3532 \n              PMD Beauty                     POLA      Santa Maria Novella \n                      13                       37                      484 \n            SERGE LUTENS                     SLIP                   TALIKA \n                    1104                      247                      675 \n            THE ORDINARY                    THREE           Valeur Absolue \n                    7113                      197                       48 \n       VAN CLEEF & ARPEL           VERSO SKINCARE                  vVARDIS \n                     882                       64                      252 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_filtered <- df_filtered %>%\n  mutate(\n    `Brand Description` = if_else(`Brand Description` == \"Masion de L\\x92asie\", \"Masion de L\",\n    if_else(`Brand Description` == \"MALIN + GOETZ\", \"MALINGOETZ.\",\n                                           `Brand Description`))\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_brands <- df_filtered %>%\n  pivot_wider(names_from = `Brand Description`, values_from = `Qty`) %>% \n  select(Customer, 23:76)\n\ndf_brands[is.na(df_brands)] <- 0\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_brand1 <- df_brands %>%\n  group_by(Customer) %>%\n  summarise(across(1:54, ~sum(.)))\n```\n:::\n\n\n### 2.1.6 Looking at the Discounts\n\nWe have earlier created the percentage discount per orders. Seems weird - but there is one with a discount of more than 100%. So we will filter that out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(df_filtered$per_discount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   0.000   2.893   0.000 232.000 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_filtered <- df_filtered %>% \n  filter(per_discount <= 100)\n```\n:::\n\n\nPlot the range of the discount:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_filtered, aes(x = per_discount)) +\n  geom_histogram(binwidth = 10, fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Histogram of Discount\", x = \"Discount\", y = \"Frequency\") +\n  theme_minimal ()\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_filtered <- df_filtered %>%\n  mutate(discount_category = cut(per_discount, breaks = c(-Inf, 0, 10, 20, 30, 40, Inf), labels = c(\"no_disc\", \"0_10\", \"10_20\", \"20_30\", \"30_40\", \"40_abv\")))\n\ndf_discount <- df_filtered %>%\n  pivot_wider(names_from = discount_category, values_from = `Qty`) %>%\n  group_by(Customer) %>%\n  summarise(across(24:29, ~sum(.)))\n```\n:::\n\n\nWe also plot the count of orders and their discount type:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_filtered, aes(x = discount_category)) +\n  geom_bar(fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Count of Orders by Discount Category\", x = \"Discount\", y = \"Frequency\") +\n  ylim(0,70000) +\n  geom_text(stat='count', aes(label=..count..), vjust=-1) + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_discount <- df_discount %>%\n  mutate(across(2:7, ~ifelse(is.na(.), \"No\", ifelse(. > 1, \"Yes\", \"No\"))))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_discount <- df_discount %>%\n  mutate(discount = ifelse(rowSums(across(2:7, ~ . == \"Yes\")) > 0, \"Yes\", \"No\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_discount, aes(x = discount)) +\n  geom_bar(fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Number of Customers who ordered with any discount\", x = \"Discount\", y = \"Frequency\") +\n  ylim(0,12000) +\n  geom_text(stat='count', aes(label=..count..), vjust=-1) + # Use stat='count' to label counts\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n# 3. Building the Customer Profile\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleft_joined_df <- \n  left_join(orders_per_customer, products_per_customer, by = \"Customer\") %>%\n  left_join(recency_per_customer, by = \"Customer\") %>%\n  left_join(samples_per_customer, by = \"Customer\") %>%\n  left_join(num_unique_customers, by = \"Customer\")  %>%\n  left_join(df_discount, by = \"Customer\") %>%\n  left_join(df_indicators, by = \"Customer\") \n\nleft_joined_df[is.na(left_joined_df)] <- 0\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(left_joined_df, \"data/customer_profile.csv\", row.names = TRUE)\n```\n:::\n\n\n## Plot the monetary value of Customers who are repeat customers vs those non-repeat \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_summary <- left_joined_df %>%\n  mutate(freq_group = ifelse(Freq == 1, \"Frequency 1\", \"Frequency > 1\")) %>%\n  group_by(freq_group) %>%\n  summarize(total_monetary = sum(Monetary))\n\n# Plot the summarized data\nggplot(df_summary, aes(x = freq_group, y = total_monetary, fill = freq_group)) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  labs(title = \"Total Monetary Value by Customer Frequency\",\n       x = \"Customer Frequency\",\n       y = \"Total Monetary Value (in Millions)\") +\n  scale_y_continuous(labels = scales::comma_format(scale = 1/1000000, suffix = \" M\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Patterns of Customer using Discount\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarize the data by counting the number of \"Yes\" values in the discount column\ndf_summary1 <- left_joined_df %>%\n  mutate(freq_group = ifelse(Freq == 1, \"Frequency 1\", \"Frequency > 1\")) %>%\n  group_by(freq_group) %>%\n  summarize(yes_count = sum(discount == \"Yes\"))\n\n# Plot the summarized data\nggplot(df_summary1, aes(x = freq_group, y = yes_count, fill = freq_group)) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  labs(title = \"Count of 'Yes' in Discount by Customer Frequency\",\n       x = \"Customer Frequency\",\n       y = \"Count of 'Yes' in Discount\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](projectanalysis_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n# Clustering using RFM\n\n-   done on SAS Viya\n",
    "supporting": [
      "projectanalysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}